--- DML

create table car_carro(
  car_id BIGINT UNSIGNED primary key AUTO_INCREMENT,
  car_marca varchar(20),
  car_placa varchar (20),
  car_modelo varchar(20)
);

CREATE TABLE USR_USUARIO (
  USR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USR_NOME VARCHAR(20) NOT NULL,
  USR_SENHA VARCHAR(50) NOT NULL,
  PRIMARY KEY (USR_ID),
  UNIQUE KEY UNI_USUARIO_NOME (USR_NOME)
);

CREATE TABLE AUT_AUTORIZACAO (
  AUT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AUT_NOME VARCHAR(20) NOT NULL,
  PRIMARY KEY (AUT_ID),
  UNIQUE KEY UNI_AUT_NOME (AUT_NOME)
);

CREATE TABLE UAU_USUARIO_AUTORIZACAO (
  USR_ID BIGINT UNSIGNED NOT NULL,
  AUT_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (USR_ID, AUT_ID),
  FOREIGN KEY AUT_USUARIO_FK (USR_ID) REFERENCES USR_USUARIO (USR_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY AUT_AUTORIZACAO_FK (AUT_ID) REFERENCES AUT_AUTORIZACAO (AUT_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

--- DDL

INSERT INTO USR_USUARIO(USR_NOME, USR_SENHA) VALUES('teste', MD5('teste'));
INSERT INTO USR_USUARIO(USR_NOME, USR_SENHA) VALUES('admin', MD5('admin'));
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_USUARIO');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_ADMIN');
INSERT INTO UAU_USUARIO_AUTORIZACAO(USR_ID, AUT_ID)
SELECT USR_ID, AUT_ID
FROM USR_USUARIO, AUT_AUTORIZACAO
WHERE USR_NOME = 'teste'
AND AUT_NOME = 'ROLE_USUARIO';
INSERT INTO UAU_USUARIO_AUTORIZACAO(USR_ID, AUT_ID)
SELECT USR_ID, AUT_ID
FROM USR_USUARIO, AUT_AUTORIZACAO
WHERE USR_NOME = 'admin';

insert into car_carro values (1, 'Chevrolet', 'DBZ8000', 'Celta');